services:

  postgres:
    image: postgres:16
    container_name: saas-boutique-central-db
    environment:
      POSTGRES_DB: saas_boutique
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: